attrib -R *.* /S
attrib -R Nt
attrib -R Nt\386
attrib -R Nt\386\bin
attrib -R Nt\386\include
attrib -R Nt\386\lib
attrib -R appl
attrib -R appl\cmd
attrib -R appl\lib
attrib -R appl\math
attrib -R appl\mux
attrib -R appl\svc
attrib -R appl\svc\httpd
attrib -R appl\svc\webget
attrib -R appl\wm
attrib -R appl\wm\brutus
attrib -R chan
attrib -R dev
attrib -R dev\draw
attrib -R dis
attrib -R dis\lib
attrib -R dis\math
attrib -R dis\mux
attrib -R dis\svc
attrib -R dis\svc\httpd
attrib -R dis\svc\webget
attrib -R dis\wm
attrib -R dis\wm\brutus
attrib -R fonts
attrib -R fonts\gb
attrib -R fonts\jis
attrib -R fonts\lucida
attrib -R fonts\lucidasans
attrib -R fonts\lucm
attrib -R fonts\misc
attrib -R fonts\pelm
attrib -R httpcache
attrib -R icons
attrib -R icons\rec-pb
attrib -R icons\tk
attrib -R icons\tk\debug
attrib -R include
attrib -R keydb
attrib -R keydb\countersigned
attrib -R keydb\signed
attrib -R lib
attrib -R lib\brutus
attrib -R lib\cmap
attrib -R licensedb
attrib -R locale
attrib -R man
attrib -R man\html
attrib -R man\html\chars
attrib -R module
attrib -R movies
attrib -R n
attrib -R n\client
attrib -R n\client\chan
attrib -R n\client\dev
attrib -R net
attrib -R n\remote
attrib -R n\ssl
attrib -R nvfs
attrib -R prog
attrib -R services
attrib -R services\comics
attrib -R services\cs
attrib -R services\email
attrib -R services\httpd
attrib -R services\news
attrib -R services\news\lnw
attrib -R services\pizza
attrib -R services\rec-pb
attrib -R services\tvlist
attrib -R services\web
attrib -R services\webget
attrib -R tmp
attrib -R usr
attrib -R usr\inferno
attrib -R usr\inferno\keyring
